#!/usr/bin/env php
<?php
// console
set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use GameLife\Command\GameLifeCommand;

$application = new Application();
$application->add(new GameLifeCommand());
$application->run();